// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 注册 HTTP 路由
// - 等价于 Java 中的 Controller+路由映射
// - 这里使用 go-zero 的 rest.Server.AddRoutes 将路径绑定到具体 Handler
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: DemoHandler(serverCtx),
			},
			// 用户 CRUD
			{Method: http.MethodPost, Path: "/users", Handler: CreateUserHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/users/:id", Handler: GetUserHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/users", Handler: ListUsersHandler(serverCtx)},
			{Method: http.MethodPut, Path: "/users/:id", Handler: UpdateUserHandler(serverCtx)},
			{Method: http.MethodDelete, Path: "/users/:id", Handler: DeleteUserHandler(serverCtx)},
		},
	)
}
